// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD11vtoA3OnosojkmGvo2OCDxyf-WszahI',
    appId: '1:1069675703211:ios:e80e7c5546e7557b9dc0ee',
    messagingSenderId: '1069675703211',
    projectId: 'icecreams-d783b',
    storageBucket: 'icecreams-d783b.firebasestorage.app',
    iosBundleId: 'com.example.deliver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD11vtoA3OnosojkmGvo2OCDxyf-WszahI',
    appId: '1:1069675703211:ios:e80e7c5546e7557b9dc0ee',
    messagingSenderId: '1069675703211',
    projectId: 'icecreams-d783b',
    storageBucket: 'icecreams-d783b.firebasestorage.app',
    iosBundleId: 'com.example.deliver',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDUl_d16vjiUEDBD4ev14vyXRgFUsN0O0',
    appId: '1:1069675703211:web:e10dd681e89785639dc0ee',
    messagingSenderId: '1069675703211',
    projectId: 'icecreams-d783b',
    authDomain: 'icecreams-d783b.firebaseapp.com',
    storageBucket: 'icecreams-d783b.firebasestorage.app',
    measurementId: 'G-NLM251XZJ4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDUl_d16vjiUEDBD4ev14vyXRgFUsN0O0',
    appId: '1:1069675703211:web:0f1d0c204b81c5e79dc0ee',
    messagingSenderId: '1069675703211',
    projectId: 'icecreams-d783b',
    authDomain: 'icecreams-d783b.firebaseapp.com',
    storageBucket: 'icecreams-d783b.firebasestorage.app',
    measurementId: 'G-JKTJJL5RGR',
  );

}